server:
  port: 8071

spring:
  application:
    name: "configserver"

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/saurabhaggarwal2017/easybank-config.git"
#          username: "saurabhaggarwal2017"
#          password: ""
          default-label: "main"
          force-pull: true
          clone-on-start: true
          timeout: 5
          search-paths:
            - accounts
            - loans
            - cards
            - eurekaconfig

#    bus:
#      trace:
#        enabled: true


#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

